title = "Конфигурационный файл"

[Client]
token = ""
requestURL = "https://api.telegram.org/bot${token}/${method}"
requestFile = "https://api.telegram.org/file/bot${token}/${filePath}"

[Aria2C]
downloadDir = "D:\\Torrent\\Downloaded"
sourcesDir = "D:\\Torrent\\Sources"
secret = ""
logDir = "D:\\Torrent\\Aria2c.log"
port = 9999
maxConnectionsPerServer = 5
maxConcurrentDownloads = 5
logLevel = "info"
