title = "Конфигурационный файл"

[Client]
token = "1051530949:AAF2ezgq49zeApjPkyRsorG1zZlQs_4OPE8"
requestURL = "https://api.telegram.org/bot${token}/${method}"
requestFile = "https://api.telegram.org/file/bot${token}/${filePath}"

[Aria2C]
downloadDir = "D:\\Torrent\\Downloaded"
sourcesDir = "D:\\Torrent\\Sources"
secret = "123"
logDir = "D:\\Torrent\\Aria2c.log"
port = 9999
maxConnectionsPerServer = 5
maxConcurrentDownloads = 5
logLevel = "info"

[DbConnection]
host     = "192.168.100.31"
port     = 5432
user     = "postgres"
password = "postgres"
dbname   = "rutrackerdb"